package api

import (
	"context"
	"net"
	"net/http"
	"net/http/httptest"
	"strconv"
	"testing"
	"time"
)

// tlsTestServer starts a local httptest TLS server (self-signed cert
// generated by net/http/httptest) and returns its host and port so tests can
// probe it with checkHostname without any live network access.
func tlsTestServer(t *testing.T) (*httptest.Server, string, int) {
	t.Helper()
	srv := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	t.Cleanup(srv.Close)

	host, portStr, err := net.SplitHostPort(srv.Listener.Addr().String())
	if err != nil {
		t.Fatalf("failed to parse listener address: %v", err)
	}
	port, err := strconv.Atoi(portStr)
	if err != nil {
		t.Fatalf("failed to parse listener port: %v", err)
	}
	return srv, host, port
}

func TestCheckHostnameReturnsChainDetails(t *testing.T) {
	_, host, port := tlsTestServer(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	result := checkHostname(ctx, host, port)

	if result.Error != "" {
		t.Fatalf("unexpected error: %s", result.Error)
	}
	if result.Subject == "" {
		t.Error("expected a non-empty leaf subject")
	}
	if result.Issuer == "" {
		t.Error("expected a non-empty issuer")
	}
	if result.RootCA == "" {
		t.Error("expected a non-empty root CA subject")
	}
	if result.ChainLength == 0 {
		t.Error("expected at least one certificate in the chain")
	}
	if result.NotAfter == "" {
		t.Error("expected a NotAfter timestamp")
	}
	if result.KeyAlgorithm == "" {
		t.Error("expected a key algorithm")
	}
	if result.Expired {
		t.Error("test certificate should not be expired")
	}
}

func TestCheckHostnameConnectionRefused(t *testing.T) {
	// Reserve a port and close it immediately so nothing is listening.
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to reserve a port: %v", err)
	}
	addr := l.Addr().String()
	l.Close()

	host, portStr, err := net.SplitHostPort(addr)
	if err != nil {
		t.Fatalf("failed to parse address: %v", err)
	}
	port, err := strconv.Atoi(portStr)
	if err != nil {
		t.Fatalf("failed to parse port: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	result := checkHostname(ctx, host, port)
	if result.Error == "" {
		t.Error("expected an error for a closed port")
	}
}
