package api

import (
	"context"
	"encoding/json"
	"net"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"testing"
	"time"
)

// tlsTestServer starts a local httptest TLS server (self-signed cert
// generated by net/http/httptest) and returns its host and port so tests can
// probe it with checkHostname/certCheckHandler without any live network
// access.
func tlsTestServer(t *testing.T) (*httptest.Server, string, int) {
	t.Helper()
	srv := httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}))
	t.Cleanup(srv.Close)

	host, portStr, err := net.SplitHostPort(srv.Listener.Addr().String())
	if err != nil {
		t.Fatalf("failed to parse listener address: %v", err)
	}
	port, err := strconv.Atoi(portStr)
	if err != nil {
		t.Fatalf("failed to parse listener port: %v", err)
	}
	return srv, host, port
}

func TestCheckHostnameReturnsChainDetails(t *testing.T) {
	_, host, port := tlsTestServer(t)

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	result := checkHostname(ctx, host, port)

	if result.Error != "" {
		t.Fatalf("unexpected error: %s", result.Error)
	}
	if result.Subject == "" {
		t.Error("expected a non-empty leaf subject")
	}
	if result.Issuer == "" {
		t.Error("expected a non-empty issuer")
	}
	if result.RootCA == "" {
		t.Error("expected a non-empty root CA subject")
	}
	if result.ChainLength == 0 {
		t.Error("expected at least one certificate in the chain")
	}
	if result.NotAfter == "" {
		t.Error("expected a NotAfter timestamp")
	}
	if result.KeyAlgorithm == "" {
		t.Error("expected a key algorithm")
	}
	if result.Expired {
		t.Error("test certificate should not be expired")
	}
}

func TestCheckHostnameConnectionRefused(t *testing.T) {
	// Reserve a port and close it immediately so nothing is listening.
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to reserve a port: %v", err)
	}
	addr := l.Addr().String()
	l.Close()

	host, portStr, err := net.SplitHostPort(addr)
	if err != nil {
		t.Fatalf("failed to parse address: %v", err)
	}
	port, err := strconv.Atoi(portStr)
	if err != nil {
		t.Fatalf("failed to parse port: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	result := checkHostname(ctx, host, port)
	if result.Error == "" {
		t.Error("expected an error for a closed port")
	}
}

func TestCertCheckHandlerReturnsResultsForAllTargets(t *testing.T) {
	_, host, port := tlsTestServer(t)

	body := `{"targets":[{"hostname":"` + host + `","port":` + strconv.Itoa(port) + `}]}`
	req := httptest.NewRequest(http.MethodPost, "/api/v1/certcheck", strings.NewReader(body))
	rec := httptest.NewRecorder()

	certCheckHandler(rec, req)

	if rec.Code != http.StatusOK {
		t.Fatalf("expected 200, got %d: %s", rec.Code, rec.Body.String())
	}

	var results map[string]HostnameCertResult
	if err := json.Unmarshal(rec.Body.Bytes(), &results); err != nil {
		t.Fatalf("failed to decode response: %v", err)
	}

	key := net.JoinHostPort(host, strconv.Itoa(port))
	res, ok := results[key]
	if !ok {
		t.Fatalf("missing result for %s in %+v", key, results)
	}
	if res.Error != "" {
		t.Errorf("unexpected error for %s: %s", key, res.Error)
	}
	if res.Issuer == "" {
		t.Errorf("expected an issuer for %s", key)
	}
}

func TestCertCheckHandlerRejectsTooManyTargets(t *testing.T) {
	targets := make([]certTarget, maxTargetsPerRequest+1)
	for i := range targets {
		targets[i] = certTarget{Hostname: "host" + strconv.Itoa(i) + ".example.com"}
	}
	payload, _ := json.Marshal(certCheckRequest{Targets: targets})

	req := httptest.NewRequest(http.MethodPost, "/api/v1/certcheck", strings.NewReader(string(payload)))
	rec := httptest.NewRecorder()

	certCheckHandler(rec, req)

	if rec.Code != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", rec.Code)
	}
}

func TestParseTarget(t *testing.T) {
	cases := []struct {
		in       string
		wantHost string
		wantPort int
	}{
		{"example.com", "example.com", defaultTLSPort},
		{"example.com:8443", "example.com", 8443},
		{"  example.com  ", "example.com", defaultTLSPort},
		{"", "", 0},
	}
	for _, c := range cases {
		host, port := parseTarget(c.in)
		if host != c.wantHost || port != c.wantPort {
			t.Errorf("parseTarget(%q) = (%q, %d), want (%q, %d)", c.in, host, port, c.wantHost, c.wantPort)
		}
	}
}

func TestNormalizeTargetsDedupesAndDefaultsPort(t *testing.T) {
	got := normalizeTargets([]certTarget{
		{Hostname: "a.example.com"},
		{Hostname: "a.example.com", Port: 443},
		{Hostname: " b.example.com ", Port: 8443},
		{Hostname: ""},
	})
	if len(got) != 2 {
		t.Fatalf("expected 2 targets, got %+v", got)
	}
	if got[0].Hostname != "a.example.com" || got[0].Port != defaultTLSPort {
		t.Errorf("unexpected first target: %+v", got[0])
	}
	if got[1].Hostname != "b.example.com" || got[1].Port != 8443 {
		t.Errorf("unexpected second target: %+v", got[1])
	}
}
