{{- include "openshift-console-metrics.assertDetected" . }}
{{- if eq (include "openshift-console-metrics.usePrometheus" .) "true" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "openshift-console-metrics.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "openshift-console-metrics.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    {{- include "openshift-console-metrics.groups" . | nindent 4 }}
{{- end }}
