{{- include "openshift-console-metrics.assertDetected" . }}
{{- if and .Values.scrapes.kubevirt.enabled (eq (include "openshift-console-metrics.usePrometheus" .) "true") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openshift-console-metrics.fullname" . }}-kubevirt
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "openshift-console-metrics.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.scrapes.kubevirt.namespace }}
  selector:
    matchLabels:
      {{- toYaml .Values.scrapes.kubevirt.matchLabels | nindent 6 }}
  endpoints:
    {{- include "openshift-console-metrics.kubevirtEndpoints" . | nindent 4 }}
{{- end }}
