{{- if .Values.extraRBAC.metrics }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "console.fullname" . }}-metrics
  labels:
    {{- include "console.labels" . | nindent 4 }}
rules:
  - apiGroups: ["console.openshift.io"]
    resources: ["consoleplugins"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "console.fullname" . }}-metrics
  labels:
    {{- include "console.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "console.fullname" . }}-metrics
subjects:
  - kind: ServiceAccount
    name: {{ include "console.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
