{{- if .Values.extraRBAC.userSettings.enabled }}
{{- $namespace := .Values.extraRBAC.userSettings.namespace | default .Release.Namespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "console.fullname" . }}-user-settings
  namespace: {{ $namespace }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "console.fullname" . }}-user-settings
  namespace: {{ $namespace }}
  labels:
    {{- include "console.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "console.fullname" . }}-user-settings
subjects:
  - kind: ServiceAccount
    name: {{ include "console.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
