#!/usr/bin/env bash
# Regenerates src/gen from proto/. Run it after editing the .proto; the output
# is committed, so neither a normal build nor the Dockerfile needs protoc.
#
# The Go side is generated by the same proto with protoc-gen-go and
# protoc-gen-connect-go -- see the README's "Regenerating the API" section.
set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v protoc >/dev/null 2>&1; then
  echo "protoc is not on PATH (brew install protobuf / dnf install protobuf-compiler)" >&2
  exit 1
fi

rm -rf src/gen
mkdir -p src/gen

protoc \
  --proto_path=proto \
  --plugin=protoc-gen-es="$PWD/node_modules/.bin/protoc-gen-es" \
  --es_out=src/gen \
  --es_opt=target=ts \
  proto/filesystem/v1/filesystem.proto

echo "regenerated src/gen from proto/"
